### ISSUE TITLE
Distance to service is not calculated correctly when last service was done when component was not installed

### ISSUE THREAD

**Issue by xivind** [xivind/velo-supervisor-2000#179]
Reported by @thomiz Distance before service is carried over, into the next service interval after servicing

**Comment by xivind** [comment]
This is fixed now. At least I am no longer able to reproduce the error. The code for this function is rewritten, and it definitely was something wrong there. Ready for review in dev @thomiz I recommend to test with only a copy of your prod db.  Please comment if you encounter further errors. Lets keep the issue open until we have merged the fix into main.

**Comment by thomiz** [comment]
Still some weirdness in the service milage calculation, the service is performed before uninstall and even so the service milage is higher than uninstalled milage:

![Image](https://github.com/user-attachments/assets/4b1e5dd8-6a75-4c3c-8f0d-8cd3bf7f863d)

**Comment by xivind** [comment]
Thank you so much for testing and reporting @thomiz Greatly appreciated. I see the exact same bug at my end. I am on it. Hoping for a fix later this evening. PS When you build from dev branch, keep in mind that automatic download of rides are disabled, so you must fetch from the config tab.

**Comment by xivind** [comment]
@thomiz finally I think this is fixed! Had to rewrite the entire process_service_records method, but now I am no longer able to reproduce the bugs you pointed out. Please let me know if this improves things at your end. Not quite ready for staging yet, but definitely ready to test. I will sort out some input validation and other minor improvements in the coming days, and after that I will get started on those other features discussed. PS Automatic download of rides is enabled again. Thanks for testing and contributing.

**Comment by thomiz** [comment]
Unfortunately not fixed completely. Still something wrong with the calculations. The service milage is off with over 100km compared to the installed, uninstalled milage.

![Image](https://github.com/user-attachments/assets/6efea309-200d-47fa-80d1-ad1099a00176)

**Comment by thomiz** [comment]
And the version info, however this is a dev version just pulled from Github but the version number is the same as two days ago?

![Image](https://github.com/user-attachments/assets/dc89528a-b5e2-44da-ba63-1fcdc2381dd3)

**Comment by xivind** [comment]
Yes, thats true @thomiz  , version is only updated in main. But a real bummer that its still not working. At my end, now all the numbers match up all the time, when comparing to ProBikeApp. Must be something I am missing here. But just to check one thing, since there is still no user documentation in place here, are we perhaps interpreting the numbers differently? The mileage field in the service record does not indicate total component distance, only distance since last service. Is the number correct you read it like that?

**Comment by xivind** [comment]
Looking at your installation records and service records, it seems correct that it is in fact 144 km since last service @thomiz In the previous version, this was for sure not working. But could it now be that the calculations are in fact correct, but displayed in a misleading manner? I have tried to improve the GUI a bit to avoid confusion and make it clearer whats totalt distance and whats distance since last service. Have a look at this screendump. Available in latest commit, in dev. No changes to calculations so far, but I will of course look into that as well, if the calculations are still off. 

![Image](https://github.com/user-attachments/assets/894e5934-62db-4e73-ba28-4253af19f0a8)

**Comment by xivind** [comment]
PS There is a small difference in the totals, but thats not an error in the main logic, just a rounding issue that becomes a bit more visible than I appreciate when there are many services..

**Comment by xivind** [comment]
@thomiz now the rounding bug is fixed, which caused a steadily increasing miscalculation as services were added. I have tested more on the main calculation logic and I think it is correct, but I may be wrong, although it looks correct with my data and the checks against ProBike. The GUI has been improved also, to better show both the total component distance accumulating across services, while the distance since last service is shown in parenthesis for each service. The accumulated distance shown on the newest service will not necessarily match the total component distance. I think thats correct, since accumulated km for components in the service log is counting kms covered by services and not complete component distance. Therefore, if no more km have been accumulated on the component since last service, the accumulated service distance should match total component distance. On the other hand, if kms have been accumulated on the component since last service, the total component distance will be higher than accumulated service distance. The two examples below illustrate both these cases.  These changes are committed now. Can you pull from dev and try to build and test again, when you have the time? You need to change a service to trigger an update, but you can just add a . or something in the description.

No more km on component after latest service (all kms are covered by services). Total service distance and total component distance match.
![Image](https://github.com/user-attachments/assets/ae2d6572-315d-473c-9b96-267736e67395)

More km on component after latest service (the km after last service is not covered by services and therefore not included in the accumulated distance service log, only in total component distance). Total service distance and total component distance should not match.
![Image](https://github.com/user-attachments/assets/b65cdd85-d361-48e2-9f02-3dee4656a560)

**Comment by thomiz** [comment]
This UI fix really clears things up 👍 

However the main problem for me is that the distance to next service is still incorrect. The bike has moved 79 km since last service+installation but it still counts the distance travelled by both chains since last service.

![Image](https://github.com/user-attachments/assets/e3396fac-8d96-4291-8b6f-e33ebfd8c979)

**Comment by xivind** [comment]
Thanks again for your patience on this one @thomiz This really improves the product. If I understand correctly, the services themselves are calculated correctly now, and the remaining problem is the distance shown under Next service. I will look closer at the method producing that field. But one question, I notice that the component has an offset. Can you try to set that to 0 and see if that changes anything? I dont think it should matter, but just to get an idea where I should focus.

Thanks for the feature request on a separate column for bike mileage. I can see how that is useful and it shouldnt be complicated to fix either. I have added it as a new issue: #182 

PS That screendump above, of component details, is that taken from a mobile? The layout looks a bit cramped. Just curious, we will get to that later, when these more important data bugs are fixed.

**Comment by thomiz** [comment]
I did update to 0 km on offset, and that was handled correctly. Km to "lifetime reached" changed, but the time to next service was not.

**Comment by xivind** [comment]
Ok, thanks! Can you send me screenshots of the complete component details page for grønn3 and grønn1, and if you could also make some changes to both these components to trigger an update, an then export the log and share that as well. Not the log shown i gui, but the docker log. I think that could help in troubleshooting this thing.

**Comment by xivind** [comment]
@thomiz I might have found something in the code that can explain the problem here. You do not need to send more screendumps and logs quite yet. But one question, is the distance to next service only wrong when component status is installed, or is it wrong, regardless of installation status?

`if latest_service_record is None:
    distance_since_service = latest_history_record.distance_marker
    matching_rides = database_manager.read_matching_rides(component.bike_id, latest_history_record.updated_date)
    distance_since_service += sum(ride.ride_distance for ride in matching_rides)
elif latest_service_record:
    matching_rides = database_manager.read_matching_rides(component.bike_id, latest_service_record.service_date)
    distance_since_service = sum(ride.ride_distance for ride in matching_rides)`

`elif component.installation_status != "Installed":
    if latest_service_record is None:
        distance_since_service = latest_history_record.distance_marker
    elif latest_service_record:
        if latest_service_record.service_date >= component.updated_date:
            distance_since_service = 0`

**Comment by xivind** [comment]
Thanks, that narrows it down! I am optimistic about solving this quite persistent bug soon and VERY relieved that the calculation of the actual service logs are behind us. This code we are discussing here is way simpler to deal with. I will get back to you!

**Comment by xivind** [comment]
@thomiz The code for calculating distance to service for installed components was indeed flawed. It counted from latest service date, instead of from most recent installation date, also it did not account for possible bike changes. That is not relevant in your case is seems, but it could perhaps be in the future, e.g. for a tire. The relevant part of the method in question (update_component_service_status) is now completely rewritten and much more robust. Considering the length of this issue, I better not claim it to be solved, but please test and see if we are on the right track. PS Distance to next service is recalculated automatically for all components  with status installed upon getting data from Strava, so if this is working, all your data should be corrected when rebuilding the container (since Strava data is pulled on startup). Everything is still in dev..

**Comment by thomiz** [comment]
Great work @xivind! The distance to next service is right on the money now 🥳

**Comment by xivind** [comment]
Thank you so much @thomiz This is a critical part of the application, so I am very glad we finally got it right. Input validations are still missing in the forms, I will look at that shortly. And then we can finally get to all these other items in the backlog that will further improve the product, e.g changing how statuses are shown and determined (e.g. no more imminent breakdown etc), accumulated bike milage pr installation and service record, collections, quick swaps, improved mobile UX and more! Thanks again for all your patience, suggestions and help in troubleshooting, its super valuable in improving the product.

**Comment by thomiz** [comment]
I just though we where out of the woods. Turns out we ai'nt. How come the chain gains km when uninstalled is beyond me.

![Image](https://github.com/user-attachments/assets/fe1b3892-64ab-4299-b3f1-a7c79df62c9f)

**Comment by thomiz** [comment]
On a similar note before uninstall: 

![Image](https://github.com/user-attachments/assets/e9c17abe-72d2-49f5-8bde-60a5e94fc8b8)

After uninstall, service interval exceeded with 146km?

![Image](https://github.com/user-attachments/assets/7c907020-da16-4cff-84b0-6f974bf73eff)

**Comment by xivind** [comment]
🤔 that is beyond me too, but not for long I hope. We will fix this one also! It looks like the last service (2025-02-08) was done after uninstall (2025-02-03). Even though the service is done after uninstall, it needs to take into account km ridden since the last service (if any). Therefore it seems reasonable that this service record has 203 km on it (which exactly seems to match with previous service 2025-01-24 and uninstall date 2025-02-03: 562-359 = 203. So if I understand you correctly, the problem here is that once again the distance to next service is displaying the wrong value, but this time when the component is uninstalled. Also, just to target the debugging, is it correct to say that the distance to next service is still calculated correctly when the component is installed, and also that the values shown in the service record are correct?
![Image](https://github.com/user-attachments/assets/a506ef54-a725-4a54-be30-4804e3b89f6f)

**Comment by thomiz** [comment]
It does not make sense at alle. The component in question have a total of 561km.

![Screenshot_20250208_202803_Chrome.jpg](https://github.com/user-attachments/assets/8a94a555-4ea8-4d2b-9e6f-754e9f738db5)

**Comment by xivind** [comment]
I think this is a problem with the part of the code that handles component service status for components that are currently not installed, and it will affect all components with that status. The last picture here, seems to be of a different component. The first two are from grønn 3 and this last one is from grønn 1? I assume you have a similar problem there, as that is also not installed? I am proceeding with the assumption that service record history is showing correct data and installed components show correct km to distance, and the problem we are dealing with now is distance to next service not correct for uninstalled components. I will look into this and get back to you.

**Comment by xivind** [comment]
I saw that the screendump of service and history logs was from grønn 1. Can you share a complete screendump of the component details page for grønn 1 and grønn 3?

**Comment by xivind** [comment]
@thomiz sorry, I am a bit to slow to catch things here. Now I see what you are saying: grønn 1 has mileage og 562, while service log says it has done 701. Agree, that obviously dont make sense. Got it! I will get back to you.

**Comment by xivind** [comment]
I pushed a bugfix this morning to dev concerning processing of first service records when multiple installation periods follow. I dont think it will solve the problem you have addressed, but it may be worth trying since the service distance are too high, and it may be caused by wrong calculation at the first one. I any case, I keep troubleshooting.

**Comment by xivind** [comment]
I understand a bit more of whats happening here now, I think. It seems to be two bugs, one is related to how the distance in the service records are created and the other is related to how distance to service is calculated for uninstalled components. For the first bug, this bugfix might fix it a75f129 At least I am not able to reproduce the error after deploying it. The other bug related to distance actually increasing when uninstalling is not yet solved, but I see what the problem is, and am working on it. Hopefully manage to have a fix in the morning.

**Comment by thomiz** [comment]
I did a thorough analysis of the calulations for GRØNN1 seems to be corect both for service and installation after your latest bugfix. (I had to force a recalculation by tweaking the time of the service records).

grønn3 seems to be off by about 30 km that is picks up at some point in the installation history. At one point I uninstalled the chain on the same date as I did a ride (earlier in the day) so the bug could be that the program messes with the timestamps when comparing installation time and ride datetime?

This [ride](https://www.strava.com/activities/13402553820)
And this installation record for Grønn3

![Image](https://github.com/user-attachments/assets/6c988885-77bd-402f-81e8-af25e86152d8)

**Comment by thomiz** [comment]
This bug seems to be fixed now:

![Image](https://github.com/user-attachments/assets/10a3729d-8712-4eed-aea9-be8f22965cc3)

Looks like this with current version:

![Image](https://github.com/user-attachments/assets/5763a80a-abe2-4e2b-b7d4-639277e5060a)

**Comment by thomiz** [comment]
The calculation error in the installation log seems to still be a problem, even after updating all the install/uninstall records:

![Image](https://github.com/user-attachments/assets/e87ed5db-4ded-4574-8b73-15cbaa72f535)

The 250 km is about 30km to high according to my own calculations.

**Comment by xivind** [comment]
Ok, thanks for your patience! I will look at it this evening and get back
to you! At least the distance to next service seems to be out of the way
(for now).

søn. 9. feb. 2025, 12:59 skrev Thomas Tveit Rosenlund <
***@***.***>:

**Comment by xivind** [comment]
I am struggling a bit to reproduce this error I am afraid. Since 250 km is too high, does that mean that the previous installation period between 19th and 14th jan  should have 136 instead of 106? I have checked the code that builds the installation history, and at first sight I cant find anything that could explain why that ride on appx 30 km earlier on 19.1,just before the installation would be included, but I will look closer. We may need to add some debug statements to print what rides are actually included when the distance marker is calculated. But let me think some more about this first. Let me know if you have other clues. PS All other numbers for that component, are they correct?

**Comment by xivind** [comment]
Never mind that question about where those 30 km were supposed to go 🤪. The answer is of course already there in the log you sent: they should be ignored altogether since they occurred  after an uninstall and before an install. I am digging. Will get back to you, but probably not today. Hope to sort this by tomorrow evening.

**Comment by xivind** [comment]
I have tried again to reproduce this error, with same sequence of installs and uninstalls as you have, and even with a ride occuring at the 19th, prior to the installation later that day, but I am not getting any unexpected km. I am missing something here for sure. It would be very helpful if you could manually query your sqlite database for each of the installation periods, and see what numbers you get. Start at the oldest period and work your way through the pairs (install - uninstall), and add the numbers as you get the query results. This way we get an idea if the problem occurs when processing the data, or if the problem is in what is returned in the query. I will be happy to do this for you, just send me your database on my email or share it some other way. If you prefer to do it yourself, you can use these commands:

**Sum km for a given period**
`SELECT SUM(ride_distance) as total_distance
FROM rides 
WHERE record_time >= '2025-02-03 12:00' 
AND record_time <= '2025-02-08 12:00';`

If you get a result that does not match what Velo Supervisor says, its interesting to know exactly what rides are summed.
**List rides for a given period**
`SELECT 
    ride_id,
    bike_id,
    record_time,
    ride_distance
FROM rides 
WHERE record_time >= '2025-02-03 12:00' 
AND record_time <= '2025-02-08 12:00';
ORDER BY record_time ASC;`

![Image](https://github.com/user-attachments/assets/822676ed-00f1-461c-aa53-8eccc6da3731)

**Comment by thomiz** [comment]
The program seem to struggle with selecting the correct rides.

This query 
~~~
SELECT  ride_id, bike_id, record_time, ride_distance FROM rides  WHERE record_time >= '2025-01-04 07:55'  AND record_time <= '2025-01-14 19:00' AND bike_id == 'b2515002' ORDER BY record_time;
~~~
returns this result:
13262921527	b2515002	2025-01-04 11:18	17.4183
13262884804	b2515002	2025-01-04 12:06	12.8872
13272261649	b2515002	2025-01-05 12:20	17.6291
13271951557	b2515002	2025-01-05 12:54	3.3693
13296465076	b2515002	2025-01-08 06:32	12.2317
13299381379	b2515002	2025-01-08 14:45	15.6075
13349332234	b2515002	2025-01-14 06:29	13.1912
13352628756	b2515002	2025-01-14 14:57	13.5717

Where 13271951557 "ride" is this [activity](https://www.strava.com/activities/13271951557)

**Comment by xivind** [comment]
Thank you so much for checking this out @thomiz This is super valuable insight! If I understand correctly we are looking at two different issues here, and both are causing the calculations to be off:

1. Rides deleted from Strava are not deleted from database, not even on a full sync
2. An activity of type ride, once it is synced to the database, will not be neither updated nor deleted from the database if its type is later changed to something else in Strava, e. g. nordic ski. The reason is that only activities of type rides are being processed, so once the activity is changed to anything else than ride in Strava, it will no longer be included and processed, leaving the original version of the activity as an orhpan in the database, messing up the calculations.. 

I was not aware of this second issue. The first issue I knew about, but considered it to be a corner case, so it was only registered back in October, but with no priority #132 . You proved me wrong there - obviously not a corner case, as you managed to trigger both of these cases in just a few months. #132 issue has now been updated to reflect both these situations. I will bump it up as well. I think maybe we need webhooks to solve it elegantly, without too much additional complexity in the processing.

But what I am really curious about, if you manually delete these two records we discuss here from your database, will the calculations in the installation log (and elsewhere) be correct then?

**Comment by xivind** [comment]
It finally seems like all bugs in the logic for calculating distances are solved, as this last bug was caused by inconsistencies in the dataset (caused by another bug #132 ), and not the logic for calculating distances itself. Setting this issue to review until its merged into main. The bug with inconsistencies in the dataset is followed up in separate issue #132
